const types = {
  // REFUND: 'REFUND',
  // BONUS: 'BONUS',
  // SUBSCRIPTION_RENEWED: 'SUBSCRIPTION RENEWED',

  SIGN_UP_BONUS: 'SIGN_UP_BONUS',
  FIVE_STAR_REVIEWS_BONUS: '5_STAR_REVIEWS_BONUS',
  REFERRAL_BONUS: 'REFERRAL_BONUS',
  SUBSCRIPTION: 'SUBSCRIPTION',
  CUSTOMER_ORDER: 'CUSTOMER_ORDER',
  PROVIDER_SALE: 'PROVIDER_SALE',
  CANCEL_SUBSCRIPTION: 'CANCEL_SUBSCRIPTION',
  SIGN_UP_BONUS: 'SIGN_UP_BONUS',
  NEW_LISTING_BONUS: 'NEW_LISTING_BONUS',
  REVIEW_BONUS: 'REVIEW_BONUS',
  TRANSFER: 'TRANSFER',
  INVIO_SUNE: 'INVIO_SUNE',
  PROFILE_BONUS: 'PROFILE BONUS',
};

const statuses = { PENDING: 'PENDING', COMPLETED: 'COMPLETED' };

module.exports = {
  types,
  statuses,
};
